from mcpacker.model.core.resourceid import ResourceId
from mcpacker.model.modpack import ModPack

# Helper Functions #################################################################################

def addDisabledFeatures(pack:ModPack):
    d = pack.disabledFeatures

    def add(resourceText:str):
        pack.disabledFeatures.append(ResourceId.parse(resourceText))

    # Disable vanilla ore generation
    add("minecraft:ore_coal_lower")
    add("minecraft:ore_coal_upper")
    add("minecraft:ore_copper_large")
    add("minecraft:ore_copper")
    add("minecraft:ore_diamond_buried")
    add("minecraft:ore_diamond_large")
    add("minecraft:ore_diamond_medium")
    add("minecraft:ore_diamond")
    add("minecraft:ore_emerald")
    add("minecraft:ore_gold_deltas")
    add("minecraft:ore_gold_extra")
    add("minecraft:ore_gold_lower")
    add("minecraft:ore_gold")
    add("minecraft:ore_iron_middle")
    add("minecraft:ore_iron_small")
    add("minecraft:ore_iron_upper")
    add("minecraft:ore_lapis_buried")
    add("minecraft:ore_lapis")
    add("minecraft:ore_redstone_lower")
    add("minecraft:ore_redstone")

    # Disable vanilla plant spawning
    add("minecraft:flower_default")
    add("minecraft:flower_flower_forest")
    add("minecraft:flower_forest_flowers")
    add("minecraft:flower_meadow")
    add("minecraft:flower_plain")
    add("minecraft:flower_plains")
    add("minecraft:flower_swamp")
    add("minecraft:flower_warm")
    add("minecraft:forest_flowers")
    add("minecraft:patch_berry_bush")
    add("minecraft:patch_berry_common")
    add("minecraft:patch_berry_rare")
    add("minecraft:patch_melon_sparse")
    add("minecraft:patch_melon")
    add("minecraft:patch_pumpkin")
    add("minecraft:patch_sugar_cane_badlands")
    add("minecraft:patch_sugar_cane_desert")
    add("minecraft:patch_sugar_cane_swamp")
    add("minecraft:patch_sugar_cane")
    add("minecraft:patch_sunflower")

    # Disable mod plant spawning
    add("corn_delight:patch_wild_corn")
    add("farmersdelight:patch_brown_mushroom_colony")
    add("farmersdelight:patch_red_mushroom_colony")
    add("farmersdelight:patch_wild_beetroots")
    add("farmersdelight:patch_wild_cabbages")
    add("farmersdelight:patch_wild_carrots")
    add("farmersdelight:patch_wild_onions")
    add("farmersdelight:patch_wild_potatoes")
    add("farmersdelight:patch_wild_rice")
    add("farmersdelight:patch_wild_tomatoes")
    add("fruitsdelight:blueberry_bush")
    add("fruitsdelight:cranberry_bush")
    add("fruitsdelight:hamimelon")
    add("fruitsdelight:lemon_tree")
    add("fruitsdelight:pineapple")
    add("fruitsdelight:tree/apple_tree")
    add("fruitsdelight:tree/bayberry_tree")
    add("fruitsdelight:tree/durian_tree")
    add("fruitsdelight:tree/fig_tree")
    add("fruitsdelight:tree/hawberry_tree")
    add("fruitsdelight:tree/kiwi_tree")
    add("fruitsdelight:tree/lychee_tree")
    add("fruitsdelight:tree/mango_tree")
    add("fruitsdelight:tree/mangosteen_tree")
    add("fruitsdelight:tree/orange_tree")
    add("fruitsdelight:tree/peach_tree")
    add("fruitsdelight:tree/pear_tree")
    add("fruitsdelight:tree/persimmon_tree")
    add("immersive_healing:medica_herb_block_spawning")
    add("realistic_wheat:wild_wheat_g")
    add("rusticdelight:wild_bell_peppers_placed")
    add("rusticdelight:wild_coffee_placed")
    add("rusticdelight:wild_cotton_placed")
    add("supplementaries:wild_flax")
