from mcpacker.model.fauna.mob import Mob
from mcpacker.model.modpack import ModPack

import mcpacker.model.fauna.active as AC


# Constants ########################################################################################

def addMobs(pack:ModPack):
    mobs = pack.world.mobs

    mobs.add(Mob("animalplus:raccoon",             AC.NOCTURNAL))
    mobs.add(Mob("animalplus:red_panda",           AC.CREPUSCULAR))
    mobs.add(Mob("bearminimum:black_bear",         AC.CREPUSCULAR))
    mobs.add(Mob("bearminimum:brown_bear",         AC.CREPUSCULAR))
    mobs.add(Mob("cold_sweat:chameleon",           AC.DIURNAL))
    mobs.add(Mob("crabbersdelight:crab",           AC.CREPUSCULAR))
    mobs.add(Mob("immersiveengineering:bulwark"))
    mobs.add(Mob("immersiveengineering:commando"))
    mobs.add(Mob("immersiveengineering:fusilier"))
    mobs.add(Mob("minecraft:armadillo",            AC.NOCTURNAL))
    mobs.add(Mob("minecraft:blaze",                AC.ANY))
    mobs.add(Mob("minecraft:bogged",               AC.MIDNIGHT))
    mobs.add(Mob("minecraft:camel",                AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:cat",                  AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:cave_spider",          AC.NOCTURNAL))
    mobs.add(Mob("minecraft:chicken",              AC.DIURNAL))
    mobs.add(Mob("minecraft:cod",                  AC.DIURNAL))
    mobs.add(Mob("minecraft:cow",                  AC.DIURNAL))
    mobs.add(Mob("minecraft:creeper",              AC.STORMY))
    mobs.add(Mob("minecraft:dolphin",              AC.DIURNAL))
    mobs.add(Mob("minecraft:donkey",               AC.DIURNAL))
    mobs.add(Mob("minecraft:drowned",              AC.MIDNIGHT))
    mobs.add(Mob("minecraft:enderman"))
    mobs.add(Mob("minecraft:evoker"))
    mobs.add(Mob("minecraft:fox",                  AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:frog",                 AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:glow_squid",           AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:goat",                 AC.DIURNAL))
    mobs.add(Mob("minecraft:hoglin"))
    mobs.add(Mob("minecraft:horse",                AC.DIURNAL))
    mobs.add(Mob("minecraft:husk",                 AC.MIDNIGHT))
    mobs.add(Mob("minecraft:llama",                AC.DIURNAL))
    mobs.add(Mob("minecraft:magma_cube",           AC.ANY))
    mobs.add(Mob("minecraft:mooshroom",            AC.DIURNAL))
    mobs.add(Mob("minecraft:mule",                 AC.DIURNAL))
    mobs.add(Mob("minecraft:ocelot",               AC.NOCTURNAL))
    mobs.add(Mob("minecraft:panda",                AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:parrot",               AC.DIURNAL))
    mobs.add(Mob("minecraft:pig",                  AC.DIURNAL))
    mobs.add(Mob("minecraft:pillager"))
    mobs.add(Mob("minecraft:polar_bear",           AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:pufferfish",           AC.DIURNAL))
    mobs.add(Mob("minecraft:rabbit",               AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:ravager"))
    mobs.add(Mob("minecraft:salmon",               AC.DIURNAL))
    mobs.add(Mob("minecraft:sheep",                AC.DIURNAL))
    mobs.add(Mob("minecraft:skeleton"))
    mobs.add(Mob("minecraft:slime",                AC.RAINY))
    mobs.add(Mob("minecraft:spider",               AC.NOCTURNAL))
    mobs.add(Mob("minecraft:squid",                AC.CREPUSCULAR))
    mobs.add(Mob("minecraft:tropical_fish",        AC.DIURNAL))
    mobs.add(Mob("minecraft:turtle",               AC.NOCTURNAL))
    mobs.add(Mob("minecraft:vex"))
    mobs.add(Mob("minecraft:villager"))
    mobs.add(Mob("minecraft:vindicator"))
    mobs.add(Mob("minecraft:wandering_trader"))
    mobs.add(Mob("minecraft:warden"))
    mobs.add(Mob("minecraft:witch"))
    mobs.add(Mob("minecraft:wither_skeleton"))
    mobs.add(Mob("minecraft:wither"))
    mobs.add(Mob("minecraft:wolf",                 AC.NOCTURNAL))
    mobs.add(Mob("minecraft:zoglin"))
    mobs.add(Mob("minecraft:zombie_villager",      AC.MIDNIGHT))
    mobs.add(Mob("minecraft:zombie"))
